version: '3.8'

services:
  bbb-recorder:
    image: jusis707/bbb-video-converter:v1
#    build: .
#    container_name: bbb-recorder
    volumes:
      - ./videos:/app/videos
    environment:
      - PRESENTATION_URL=${PRESENTATION_URL}
      - RECORDING_DURATION=${RECORDING_DURATION}
      - RECORDING_ID=${RECORDING_ID}
      - DISPLAY=:99
    shm_size: 5gb
